### ISSUE TITLE
USB Keyboard Driver Question

### ISSUE THREAD

**Issue by lonnietc** [FRosner/FrOS#4]
Hello,

I was reading over your "Writing My Own Keyboard Driver" (https://dev.to/frosnerd/writing-my-own-keyboard-driver-16kh) about the keyboard driver in which you mentioned that USB keyboards have a different scan code but you did not give much information on it.

I am working on updating an OS drive that was written to read PS/2 keyboards but now dose not work with modern USB keyboards and mouse interfaces. 

I need to learn how to write an updated drive to hand USB keyboards and mouse devices.

Do you have any guidance or suggestions?

**Comment by FRosner** [comment]
I don't, sorry!
